package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionDB {
    // Déclaration des variables pour la connexion à la base de données
    private String strClassName = "com.mysql.cj.jdbc.Driver"; // Nom du driver MySQL
    private String dbName = "allergomenu2_bdd"; // Nom de la base de données
    private String login = "397727"; // Identifiant de connexion
    private String mdp = "W34reSomeMi!@"; // Mot de passe
    private String dbUrl = "jdbc:mysql://mysql-allergomenu2.alwaysdata.net/"+dbName+"?serverTimezone=UTC"; // URL de connexion JDBC

    private Connection conn;
    private PreparedStatement ps;


    // Constructeur permettant d'initialiser les informations de connexion
    public  ConnectionDB() {
    	try {
            if (conn == null || conn.isClosed()) {
                // Chargement du driver MySQL
                Class.forName(strClassName);
                // Établissement de la connexion avec la base de données
                this.conn = DriverManager.getConnection(dbUrl, login, mdp);
                System.out.println("Connexion à la base de données réussie.");}
            else {
            	System.out.println("Echec de la connexion à la base de données.");
            }

        } catch (ClassNotFoundException e) { // Gestion de l'exception si le driver n'est pas trouvé
            System.err.println("Driver non chargé !");
            e.printStackTrace();
        } catch (SQLException e) { // Gestion des erreurs SQL
            System.err.println("Erreur SQL : " + e.getMessage());
        }
    };


	public Connection getConnection() {
        return this.conn;
    }

    // Méthode pour initialiser un PreparedStatement avec une requête SQL
    public void initPreparedStatement(String sql) {
    	if (conn == null) {
        	System.err.println("Erreur : La connexion à la base de données n'a pas été établie. Assurez-vous d'appeler getConnection() avant d'utiliser un PreparedStatement." );
            }
	         try {
	            ps = conn.prepareStatement(sql);

	        } catch (SQLException e) {
	            System.err.println("Erreur lors de l'initialisation du PreparedStatement : " + e.getMessage());
	            e.printStackTrace();

	        }
	}
    
    //Surcharge utilisée pour récupérer l'id de la recette à sa création et de l'utilisateur aussi
    public void initPreparedStatement(String query, int autoGeneratedKeys) throws SQLException {
        ps = conn.prepareStatement(query, autoGeneratedKeys);
    }

    public PreparedStatement getPrepareStatement() {
    	return this.ps;
    }


 // Méthode pour fermer la connexion à la base de données et le prepareStatement
    public void closeConnection() {
        try {
            if (ps != null) {
                ps.close();
                System.out.println("Prepare Statement fermée.");
            }
            if (conn != null) {
                conn.close();
                System.out.println("Connexion fermée.");
            conn = null;
            }
        } catch (SQLException e) {
            System.err.println("Erreur lors de la fermeture : " + e.getMessage());
        }
}





}
